# Generated by Django 4.2.11 on 2024-04-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('decimal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precisao', models.IntegerField()),
                ('binario', models.CharField(max_length=255)),
                ('octal', models.CharField(max_length=255)),
                ('hexadecimal', models.CharField(max_length=255)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
