# Generated by Django 4.2.11 on 2024-04-23 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversao',
            old_name='novo_id',
            new_name='id',
        ),
    ]
