# Generated by Django 4.2.11 on 2024-04-23 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0002_rename_novo_id_conversao_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conversao',
            new_name='Convert',
        ),
    ]
