# Generated by Django 4.2.11 on 2024-04-23 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0003_rename_conversao_convert'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Convert',
            new_name='Conversao',
        ),
    ]
