# Generated by Django 4.2.11 on 2024-04-23 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0004_rename_convert_conversao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conversao',
            new_name='Convert',
        ),
    ]
