version: '3.9'

services:
  dj_bohconvert:
    container_name: dj_bohconvert_test
    image: alexandre11aa/bohc:latest
    ports:
      - 8000:8000
    environment:
      SECRET_KEY: "cc90682b9f1e12d7a9d23c63d0b4e9e01dbcd55ba9ddda2b"
      DEBUG: "1"
      ALLOWED_HOSTS: "127.0.0.1, localhost"
      DB_ENGINE: "django.db.backends.postgresql"
      POSTGRES_DB: "bohconvert_db"
      POSTGRES_USER: "bohconvert_db_user"
      POSTGRES_PASSWORD: "bohconvert_db_password"
      POSTGRES_HOST: "psql"
      POSTGRES_PORT: "5432"
    depends_on:
      - psql
  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "bohconvert_db"
      POSTGRES_USER: "bohconvert_db_user"
      POSTGRES_PASSWORD: "bohconvert_db_password"